# tasks file for nginx-role
- name: Install Nginx
  apt:
    name: nginx
    state: latest
  become: true

- name: Enable and start Nginx
  service:
    name: nginx
    enabled: yes
    state: started
  become: true

- name: Deploy webapp
  copy:
    src: index.html
    dest: /var/www/html/index.html
  become: true
